# Generated by Django 3.0.6 on 2020-05-29 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_propertyimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimg',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
