# Generated by Django 3.0.6 on 2020-05-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_auto_20200529_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimg',
            name='uuid',
            field=models.ImageField(upload_to=''),
        ),
    ]
