# Generated by Django 3.0.6 on 2020-05-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_auto_20200529_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimg',
            old_name='uuid',
            new_name='img',
        ),
    ]
